services:
  Crmp\BaseBundle\Controller\AuthController:
    class: Crmp\BaseBundle\Controller\AuthController
    arguments:
      - '@crmp\basebundle\repository\addressrepository'
    calls:
      - ['setContainer', ['@service_container']]
