services:
  Crmp\BaseBundle\Repository\AddressRepository:
    class: Crmp\BaseBundle\Repository\AddressRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Crmp\BaseBundle\Entity\Address
