language: php
sudo: required

# PHP Support see: http://php.net/supported-versions.php
# HHVM Support see: https://docs.hhvm.com/hhvm/installation/introduction#lts-releases
matrix:
  include:
    # Drop PHP 5.6 on 31 Dec 2018
    - php: '5.6'
    # Drop PHP 7.0 on 3 Dec 2018
    - php: '7.0'
    - php: '7.1'
    # Drop HHVM 3.12 on 29 Dec 2016
    - php: hhvm-3.12
      dist: trusty
      group: edge
    # Drop HHVM 3.15 on 15 Jun 2017
    - php: hhvm-3.15
      dist: trusty
      group: edge
    # Add HHVM 3.18 on 13 Feb 2017
    # - hhvm-3.18

env:
  matrix:
    - ENV=dev
    - ENV=prod
    - ENV=test

services:
  - mysql

before_script:
  #- cp app/config/parameters.yml.travis app/config/parameters.yml
  #- mysql -e 'create database crmp;'
  - composer install
  #- bin/console doctrine:schema:create --env=$ENV
  - bin/console cache:warmup
  #- bin/console server:run 127.0.0.1:8000 --env=$ENV &
  #- bin/populate.sh


script:
  # Assert composer.json is clean
  - composer validate --strict
  # Run unit tests
  - vendor/bin/phpunit --coverage-clover=var/phpunit/coverage.xml --coverage-text
  # CodeSniffer
  #- vendor/bin/phpcs --config-set installed_paths opt/escapestudios/symfony2-coding-standard
  #- vendor/bin/phpcs --standard=etc/phpcs.xml src
  # - vendor/bin/behat --no-colors -f progress

after_success:
  - bash <(curl -s https://codecov.io/bash)
